# Travis configuration file using the build matrix feature
# Read more under http://docs.travis-ci.com/user/build-configuration/
# THIS SCRIPT IS SUPPOSED TO BE AN EXAMPLE. MODIFY IT ACCORDING TO YOUR NEEDS!

dist: bionic
sudo: false
language: python
virtualenv:
  system_site_packages: false
matrix:
  fast_finish: true
  include:
    - python: 3.7
      env: DISTRIB="bionic" TOX_PYTHON_VERSION="py37" COVERAGE="true"
    - env: DISTRIB="conda" PYTHON_VERSION="3.7" COVERAGE="false"
install:
  - source tests/travis_install.sh
  - pip install -r requirements_dev.txt
  # ^  DEPRECATION WARNING:
  # The automatic creation of a `requirements.txt` file is deprecated.
  # See `Dependency Management` in the docs for other options.
before_script:
  - git config --global user.email "kamikaze.is.waiting.you@gmail.com"
  - git config --global user.name "Oleg Korsak"
script:
  - python setup.py develop
  - tox
  - |
    if [[ "$COVERAGE" == "true" ]]; then
      pre-commit install
      pre-commit run --all-files
    fi
after_success:
  - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
  - if [[ "$COVERAGE" == "true" ]]; then codecov || echo "failed"; fi
after_script:
  - travis-cleanup
cache:
  pip: true
  directories:
    - $HOME/miniconda

#deploy:
#  provider: pypi
#  distributions: bdist_wheel
#  user: kamikaze
#  password:
#    secure: R9UvpiT9OFvwaMb9IFdC2OX98t+X81DMLDJE0u0DeShJqtll5Voa81RfULeo+V7afqYNA7aFP7qitGjaUDXIGQ2FghgbYO7w2doDOI2jSDa+VNSckCrdoaCigJ/C8QkFGvkt5g21zL1gkQhxWXJGLCudGYEKT9OBPM/Q/ce4SF3DSF1cdRb3SIPuVeV4/GW/dquqG3Tfxm2wDKi96BCy7259fNwKNL0wj6ENaD4+A50IQfOo9vE9ul0JZJvpS4H2vs3yeegXuuMJuOCtmdc6qDmDjj2nFzBiF53E/E88Y4D99v81klJrW59TnrTqEs+e6twDG7ind+vRRGoX4bes5MSRUnhayyz23mIRmh/NQCYlXbS1m53aG31GJfn6JbkXGrzCgjZ9B3bioWDMvvGMLjRGRkKUSuPQF9MaBbWQElT3Fw3+v7FNrVo40yHO5+QrCTgKPoyQ12Hdse9d/omx0RgnBz10pHGgNo+A+WT/Ix4EM4IctELqfz1yYsp0kcO7AfT5wH9tOfwMZaNs5lkkK2ePpcqowl3sdAzkN6IBkkHZirCtLRtHz8wgMZa/pj6i4vBClH1hfXiwSmaDIqgPgXOzb+jP4kuofEROZ2+Pyjhi7vZj8wnehBewO8qsMp17D9fRJrtf9uofCXFvMN1spFZWKueS4pnQuyoHbtM8M6U=
#  on:
#    tags: true
#    repo: kamikaze/aiofm
#    python: 3.7
